spring:
  application:
    name: ws-account
    title: ws-account
  datasource:
    url: ${DATABASE_URL}
    driverClassName: "org.postgresql.Driver"
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8081
  servlet:
    context-path: /ws-account

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
